### ISSUE TITLE
Install on Ubuntu fails due to wrong GPG Keys

### ISSUE THREAD

**Issue by FBaumeister** [LinkedInLearning/learning-jenkins-3003221#2]
## Issue Overview
Unable to install Jenkins on Ubuntu 22.04 LTS.

## Describe your environment
Fresh setup of a Ubuntu 22.04.2 LTS Server in Oracle VM Box.

## Steps to Reproduce
Follow the instructions from Chapter 1.5 to install Jenkins on Ubuntu.

## Expected Behavior
Successful Jenkins installation as performed in the video.

## Current Behavior
Unable to perform the _sudo apt update_ command successfully.
Got complaints on a missing / wrong GPG-Signature.

## Possible Solution
The solution seems to be described here, as the keys have changed:
https://www.jenkins.io/blog/2023/03/27/repository-signing-keys-changing/
Executing the command from the jenkins-blog I was able to perform the update and the installation.

**Comment by managedkaos** [comment]
Fixed.
